export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_REMINDERS = 'GET_REMINDERS';
export const ADD_REMINDER = 'ADD_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER'
export const UPDATE_REMINDER = 'UPDATE_REMINDER'

export const GET_ERRORS = 'GET_ERRORS';
